language: node_js
node_js: 10
before_script:
  - npm install -g firebase-tools
  - npm install -g firebase-functions
script:
  - firebase deploy --project foundingbuddies-8f157 --token $FIREBASE_TOKEN
